config/routes.rb
WdyMeasure::Application.routes.draw do

  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :categories,       only: [:index, :show]
    resources :instrument_kinds, only: [:index, :show]

    resources :instruments,      only: [:create] do
      collection do
        post 'unique'
        post 'search'
      end
    end

    resources :verifications,    only: [:create]
    resources :organs,           only: [:index]
    resources :roles,            only: [:index]

    resources :users,            only: [:index, :create] do
      member do
        post 'approve'
      end
    end

    resources :early_warnings do
      collection do
        get "expires"
        get "scraps"
      end
    end
  end

  resources :notifications, only: [:index, :show]
  get "datalogs" => 'data_logs#index'
  resources :inspections

  resources :notices do
    member do
      get 'edit_inside_page'
      patch 'update_content'
    end
    collection do
      get 'search'
    end
  end

  resources :users
  resources :settings do
    collection do
      get 'organ'
    end
  end

  resources :regulations
  resources :verifications do # 检测检定
    member do
      get 'report'
      get 'certificate'
      post 'calculate'
    end
    collection do
      get 'update_state'
      get 'organ'
      get 'imports'
      post 'process_import'
    end
  end
  resources :reports   # 检定数据报告（检定纪录）
  resources :organs    # 组织单位

  resources :categories do # 分类
    resources :category_types # 类型
    resources :category_ranges # 范围
    resources :category_precisions  # 精度
  end

  get 'instruments/search/:query', to: 'instruments#search', as: 'search'
  get 'instruments/search', to: 'instruments#search'
  resources :instruments do 
    collection do 
      get 'expires'
      get 'scraps'
    end
  end

  resources :vendors
  resources :tasks

  namespace :wdy do
    namespace :unirole do
      resources :organs
      resources :jobs
      resources :users
    end
  end

  resources :instrument_kinds

end

app/models/verification.rb
# -*- coding: utf-8 -*-
class Verification < Sequel::Model(:verifications)
  plugin :validation_helpers
  plugin :active_model
  many_to_one :instrument,class_name: "Instrument", key: 'instrument_id'
  one_to_one :report,class_name: "Report"
  many_to_one :organ,class_name: "Organ"
  many_to_one :standard, class_name: "Instrument", key: "standard_id"
  one_to_many :notices
  many_to_one :user

  def validate
    super
    validates_presence [:instrument_id, :organ_id, :date], message: '不能为空'
  end

 class << self
    %w|registered examined verified|.each do |status|
      define_method "#{status}" do
        Verification.where("state = ?", status)
      end
    end
  end

  def notice
    self.notices_dataset.where(expired: false).last
  end

  def generate_notice
    notice = Notice.create(verification_id: self.id, instrument_id: self.instrument_id, organ_id: self.instrument.organ_id)
    mark_old_notice_as_expired(notice)
    save_notice_content(notice)
  end

  def mark_old_notice_as_expired(notice)
    self.instrument.notices_dataset.where("id != ? AND expired = ?", notice.id, false).update(expired: true)
  end

  def save_notice_content(notice)
    data = self.report.data.blank? ? Report.default_data(self) : JSON.parse(self.report.data)
    notice.certificate = data['qualified'] ? 1 : 0
    if data['计算结果'.force_encoding('utf-8')]
      content = data['计算结果'.force_encoding('utf-8')].merge(data['result']).merge(qualified: data['qualified'])
      notice.content = content.to_json
    end
    notice.save
  end

  def after_create
    super
    report = Report.create(verification_id: self.id)
    self.update(report_id: report.id)
  end

  state_machine :state, initial: :registered do

    event :examined do
      transition [:registered] => :examined
    end

    event :verified do
      transition [:examined] => :verified
    end

    event :approved do
      transition [:verified] => :approved
    end
  end
end

app/controllers/api/verifications_controller.rb
# -*- coding: UTF-8 -*-

# 检定过程
class Api::VerificationsController < CasActionController

      # before_filter :fix_cas_session
      # before_filter :ensure_loggedin

      # def fix_cas_session
      #   if session[:cas].respond_to?(:with_indifferent_access)
      #     session[:cas] = session[:cas].with_indifferent_access
      #   end
      # end

      # def ensure_loggedin
      #   if session[:cas].nil? || session[:cas][:user].nil?
      #     render status: 401, text: "Redirecting to SSO..."
      #   end
      # end

      # helper_method :current_user

      # def current_user
      #   return @current_user if @current_user
      #   if cas = request.session['cas']
      #     @current_user = CurrentUser.new
      #     @current_user.username = cas['user']
      #     @current_user.id = User.find_or_create(
      #         username: @current_user.username,
      #         email: "#{@current_user.username}@cnpc.com.cn").id
      #     @current_user.abilities = cas['extra_attributes']
      #     return @current_user
      #   end
      # end




    def create
        sn = params[:data]["sn"]
        instrument = Instrument[sn: sn]

        req = params[:data].clone
        req.delete("verification")

        instrument = Instrument.create(req) if instrument.blank?
        verification = Verification.create(
            params[:data]["verification"].merge(instrument_id: instrument.id, user_id: current_user.id))

        render json: verification
    end
end

app/controllers/verifications_controller.rb
# encoding: UTF-8
# 检测检定
class VerificationsController < ApplicationController
  load_and_authorize_resource class: "Verification"
  before_filter :check_file, only: [:process_import]

  def index
    @page_title = "检测检定管理"
    @verifications = Verification.order(:organ_id, :instrument_id).all
  end

  def organ
    @page_title = "检测检定管理"
    @verifications = Verification.order(:organ_id, :instrument_id).where(organ_id: current_user.organ_id)
  end

  def report
    @verification = Verification[id: params[:id]]
    @instruments = Instrument.where(standard: 1).all
    @data = @verification.report.data.blank? ? Report.default_data(@verification) : JSON.parse(@verification.report.data)
    render "reports/#{Settings.reports.send(@verification.instrument.instrument_kind.name)}"
  end

  def certificate
    # TODO: Read the certificate data from verification's notice
    @verification = Verification[id: params[:id]]
    @standard = @verification.standard
    @content = JSON.parse(@verification.notice.content)
    result_type = @content['qualified'] ? "证书" : "通知书"
    filename = "#{@verification.date}-#{@verification.organ.name}-#{@verification.instrument.detection_name}-#{result_type}"
    respond_to do |format|
      format.pdf do
        render pdf: filename,             # file name
               #template: 'layouts/application.pdf.slim',
               #layout: 'layouts/application.pdf.slim',
               #show_as_html: true
               layout: 'layouts/application.pdf.slim'
      end
    end
  end

  def calculate
    verification = Verification[params[:id]]
    verification.update(sn: params[:report]['纪录编号']) if params[:report]['纪录编号']
    @record = Report.verify verification, params[:report]
    is_certificate = @record['result']['pass'] ? 1 : 0
    verification.examined! if !verification.examined?

    if params[:report]['检定日期']
      verification.report.update(verification_date: params[:report]['检定日期'])
    end
    if params[:report]['核验日期']
      verification.report.update(checked_date: params[:report]['核验日期'])
    end
    redirect_to report_verification_path(params[:id])
  end

  def create
    if params[:instrument][:sn].present?
      @instrument = Instrument[sn: params[:instrument][:sn]]
      if @instrument.blank?
        @instrument = Instrument.create(instrument_params)
      end
      @verification = Verification.new(params[:instrument][:verification].merge(instrument_id: @instrument.id, user_id: current_user.id))
      if @verification.valid? and @verification.save
        redirect_to report_verification_path(@verification), success: '申请成功.'
      else
        flash[:alert]='请填写所有输入框数据'
        render :action=>:new
      end
    else
      flash[:alert]='请填写所有输入框数据'
      render :action=>:new
    end
  end

  def update
    if @verification.update(params[:verification])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def update_state
    verification = Verification[params[:id]]
    verification.send("#{params[:state]}!")
    if params[:state].inquiry.approved?
      verification.generate_notice
    end

    if params[:state].inquiry.examined?
      redirect_to report_verification_path(verification)
    else
      redirect_to root_path
    end
  end
  #
  # def show
  # end

  def destroy
    @verification.destroy
    redirect_to :action => :index
  end

  def process_import
    @messages = ImportFile.import(@file,current_user.id)
    render "process_import"
  end

  private
  def check_file
    @file = params[:import_file]
    unless (@file.original_filename.split(".")[1]).to_s.eql?("xlsx")
      redirect_to action: :imports
    end
  end

  def instrument_params
    params.require(:instrument).permit(:sn,:organ_id,:instrument_kind_id,:specification,:date,
                                      :vendor_id,:category_id,:category_precision_id,
                                      :category_range_id,:basis, :regulation_id)
  end
end

app/helpers/verification_helper.rb
module VerificationHelper
  def etalon_indicating_values
    %w(0 0.6 1.2 1.8 2.4 3 3.6 4.2 4.8 5.4 6)
  end
  def style_next_check_time(date)
    return "" if date.blank?
    date += 1.year
    if date > (Date.today + 1.month)
      ""
    elsif date > Date.today
      "#fee188"
    else
      "#d15b47"
    end
  end
end

app/views/verifications/_conclusion.html.erb
<%- if result.present? %>
  <%- if result['pass']%>
    <span class="blue">
      <%= "符合#{precision}级"%>
    </span>
  <%- else %>
    <span class="red">
      <%= "不符合#{precision}级"%>
    </span>
    <%= render partial: 'failure', locals: {message: result['message']} %>
  <% end %>
<% end %>

app/views/verifications/_conclusion.pdf.slim
- if result.present?
  - if result['pass']
    span class="blue"
      = "符合#{precision}级"
  - else
    span class="red"
      = "不符合#{precision}级"

app/views/verifications/_cover.pdf.slim
br
.cover
  h4
    | 西南油气田分公司蜀南气矿计量站
  h3
    - if @report['result']['pass']
      |  检定证书
    - else
      |  检定通知书
  p.center
    | 证书编号：
    span.input-line[style="width:130px;"]
      = @verification.sn
  .cover-content
    .cover-item
      label
        | 送 检 单 位
      span.input-line
        = @verification.organ.name
    .cover-item
      label
        | 计 量 器 具 名 称
      span.input-line
        = @verification.instrument.instrument_kind.name
    .cover-item
      label
        | 型 号 / 规 格
      span.input-line
        = @verification.instrument.specification
    .cover-item
      label
        | 出 厂 编 号
      span.input-line
        = @verification.instrument.sn
    .cover-item
      label
        | 制 造 单 位
      span.input-line
        = @verification.instrument.vendor.name
    .cover-item
      label
        | 检 定 依 据
      span.input-line
        = @verification.instrument.regulation.try(:sn)
    .cover-item
      label
        | 检 定 结 论
      span.input-line
        = render partial: 'conclusion', locals: {result: @report['result'], precision: @verification.instrument.try(:precision)}
    .row[style="margin-top: 35px;"]
      table.table-align
        tr
          td
          td
            .cover-item
              label[style="width: 60px;"]
                | 批 准 人
              span.input-line[style="width: 150px;"]
                = @report['批准人']
        tr
          td
            span
              | (检定专用章)
          td
            .cover-item
              label[style="width: 60px;"]
                | 核 验 员
              span.input-line[style="width: 150px;"]
                = @report['核验员']
        tr
          td
          td
            .cover-item
              label[style="width: 60px;"]
                | 检 定 员
              span.input-line[style="width: 150px;"]
                = @report['检定员']
      .clearfix
    div[style="margin-top: 30px;"]
      p.center
        | 检定日期
        span[style="margin-left: 20px;"]
          = @verification.created_at.to_date.strftime("%Y年%m月%d日")
      - if @report['result']['pass']
        p.center
          | 有效期至
          span[style="margin-left: 20px;"]
            = (@verification.created_at + 1.year).to_date.strftime("%Y年%m月%d日")
  .row.cover-footer
    table.table-align
      tr
        td
          | 地址：四川.泸州
        td
          | 电话：0830-3922078
      tr
        td
          | 传真：0830-3922078
        td
          | 邮编：646300
      tr
        td &nbsp;
        td
          | Email:sn_ilz@petrochina.com.cn

app/views/verifications/_failure.html.erb
<span class="red">
  <%- message.each do |key,value|%>
    <p>
    <%= key %>:
    <% value.each do |name,differential| %>
      <span>
        <%= "#{name}-#{differential}"%>
      </span>
    <% end %>
    </p>
  <% end %>
</span>

app/views/verifications/_failure.pdf.slim
span.red
  - message.each do |key,value|
    p
      = key
      | : 
      - value.each do |name,differential|
        span
          = "#{name}-#{differential}"

app/views/verifications/_form.slim
= f.input :instrument_id,:label => "计量器具编号" do
  = f.select :instrument_id,Instrument.all.collect{|p|[p.sn,p.id]},{:include=>"_blank"},{:class=>"selectpicker col-sm-2"}
= f.input :organ_id, label: "送检单位" do
  = f.select :organ_id,Organ.all.collect{|p|[p.name,p.id]},{:include=>"_blank"},{:class=>"selectpicker col-sm-2"}
= f.input :date,label: "送检日期",input_html: {onclick: "WdatePicker({onpicked: function(){$(this).trigger('change')}})"}
.form-actions
  = f.button :submit,"提交", class: 'btn-info'

app/views/verifications/_verifications.slim
.table-header
  | 检定记录
  div class="widget-toolbar no-border"
    a  class="btn btn-primary"  href=new_verification_path 添加
.table-responsive
  table.table.table-bordered.table-striped.table-hover  id="verification_table"
    tfoot
      tr
        th 序号
        //th 检定单位
        th 计量器具名称
        th 计量器具编号
        th 生产日期
        th 生产厂商
        th 测量范围
        th 准确度等级
        th 检定分类
        //th 上次检定日期
        th 送检日期
        th 检定日期
        th 下次检定日期
        th 标准器信息
        th 检定单位
        //th 检定人
        th 检定依据
        //th 检定结论
        th 检定证书编号
        th 状态
        th
    thead
      tr
        th 序号
        //th 检定单位
        th 计量器具名称
        th 计量器具编号
        th 生产日期
        th 生产厂商
        th 测量范围
        th 准确度等级
        th 检定分类
        //th 上次检定日期
        th 送检日期
        th 检定日期
        th 下次检定日期
        th 标准器信息
        th 检定单位
        //th 检定人
        th 检定依据
        //th 检定结论
        th 检定证书编号
        th 状态
        th
    tbody
      -@verifications.each_with_index do |verification,index|
          tr
            td =index=index+1
            //td =verification.organ.name
            td =verification.instrument.try(:detection_name)
            td =verification.instrument.sn
            td =verification.instrument.try(:date)
            td =verification.instrument.vendor_name
            td =verification.instrument.try(:detection_range)
            td =verification.instrument.try(:detection_precision)
            td =verification.instrument.category.name
            td =verification.date
            td =verification.report.checked_date
            td style="background-color:#{style_next_check_time(verification.report.checked_date)}"
              =verification.report.checked_date.nil? ? verification.report.checked_date : verification.report.checked_date + 1.year
            td
              - if verification.instrument.standard ==1
                span style="color:red"  是
              - else
                span  否
            td =verification.organ.name
            //td =verification.instrument.sn
            td =verification.instrument.regulation.try(:sn)
            td =verification.sn
            td =Settings.state.send("#{verification.state}")
            td
              div class="pull-right action-buttons"
                - if (can? :certificate, Verification) && verification.notice && verification.state == "checked"
                  a class="blue" href=notice_path(verification.notice) data_toggle='tooltip' title="查看证书" target="_blank"
                    i class="fa fa-registered"
                - if can? :report, Verification
                  a class="blue" href=report_verification_path(verification) data_toggle='tooltip' title="显示"
                    i class="fa fa-crosshairs"
                - if can? :update, Verification
                  a class="blue" href=edit_verification_path(verification) data_toggle='tooltip' title="编辑"
                    i class="fa fa-edit"
                - if can? :destroy, Verification
                  span class="vbar"
                  =link_to "<i class='fa fa-trash'></i>".html_safe,verification_path(verification),method: "delete", data_toggle: 'tooltip', title: "删除", data: { confirm: "您确定要删除此类型？"},class: "red"
                  span class="vbar"
javascript:
  $('#verification_table tfoot th:nth-child(n+1):nth-child(-n+16)').each(function () {
    var title = $('#verification_table thead th:nth-child(n+1):nth-child(-n+16)').eq($(this).index()).text().trim();
      $(this).html( '<input type="text" style="width:90%;" placeholder="搜索'+title+'" />' );
  });
  var oTable = $('#verification_table').DataTable({
    "oLanguage": {//语言国际化
      //"sUrl": "js/jquery.dataTable.cn.txt"
      "sLengthMenu": "每页显示 _MENU_ 条记录",
      "sZeroRecords": "抱歉， 没有找到",
      "sInfo": "从 _START_ 到 _END_ /共 _TOTAL_ 条数据",
      "sInfoEmpty": "没有数据",
      "sInfoFiltered": "(从 _MAX_ 条数据中检索)",
      "oPaginate": {
      "sFirst": "首页",
      "sPrevious": "前一页",
      "sNext": "后一页",
      "sLast": "尾页"
      },
      "sZeroRecords": "没有检索到数据",
      "sProcessing": "   处理中...",
      "sSearch": "全文搜索"
    },
    "scrollX": true,
    "initComplete" : function () {
      $('.dataTables_scroll').parent().removeClass();
    }
  });
  oTable.columns().every(function () {
    var that = this;
    $('input', this.footer()).on('keyup change', function(){
      that.search(this.value).draw();
    });
  });

app/views/verifications/certificate.pdf.slim
= render partial: 'verifications/cover', formats: [:pdf]
.page-break
= render partial: "certificates/#{Settings.certificates.send(@verification.instrument.instrument_kind.name)}", formats: [:pdf]

app/views/verifications/edit.slim
.widget
  h4
    span.text-info 编辑检定纪录信息
  hr class="hr-18 dotted hr-double"
  .widgetarea
    = simple_form_for @verification, :html => {:class=>"form-horizontal form-mini"} do |f|
      =render "form",:f =>f

app/views/verifications/imports.slim
link rel="stylesheet" href="/css/typeahead.css"
.widget
  h4
    span.text-info 待检计量器具信息
  hr class="hr-18 dotted hr-double"

  .widgetarea
    = form_tag process_import_verifications_path, method: :post, multipart: true do
      input type="file" name="import_file"

      button type="submit" 导入

    div
      span 按照该模版构建数据
      a href="/template.xlsx" 模版

app/views/verifications/index.slim
= render 'verifications'

app/views/verifications/new.slim
link rel="stylesheet" href="/css/typeahead.css"
.widget
  h4
    span.text-info 待检计量器具信息
  hr class="hr-18 dotted hr-double"

  .widgetarea
    = simple_form_for :instrument,url: verifications_path, method: :post, :html => {:class=>"form-horizontal form-mini"} do |f|
      div class="form-group string required instrument_category_id"
        label for="instrument_category_id" class="string required col-sm-3 control-label"
          abbr title="required" *
          | 计量器具编号
        div class="col-sm-9"
          = f.input_field :sn, class: 'typeahead'
          span style="margin-left:10px;"
            a.btn.btn-info.btn-xs.btn-success href='#' style="margin-top:5px;" id='autofill'
              | 自动填充
      =f.input :organ_id, as: :hidden, input_html: {value: current_user.organ_id}
      = f.input :category_type_id do
        = f.select :category_type_id,CategoryType.with_report.collect{|p|[p.name,p.id]},{:include=>"_blank"},{:class=>"selectpicker col-sm-2"}
      =f.input :specification,:label => "规格型号"
      =f.input :date,:input_html => { :onclick =>  "WdatePicker({onpicked: function(){$(this).trigger('change')}})"}
      div class="form-group string required instrument_category_id"
        label for="instrument_category_id" class="string required col-sm-3 control-label"
          abbr title="required" *
          | 生产厂商
        div class="col-sm-9"
      	 =f.select :vendor_id,Vendor.collect{|p|[p.name,p.id]},{},{:class=>"chosen-select"}
      div class="form-group string required instrument_category_id"
        label for="instrument_category_id" class="string required col-sm-3 control-label"
          abbr title="required" *
          | 检定分类
        div class="col-sm-9"
      	 =f.select :category_id,Category.collect{|p|[p.name,p.id]},{},{:class=>"selectpicker col-sm-2"}

      = f.input :category_precision_id do
        = f.select :category_precision_id,CategoryPrecision.all.collect{|p|[p.precision,p.id]},{include_blank: true},{:class=>"selectpicker col-sm-2"}
      = f.input :category_range_id do
        = f.select :category_range_id,CategoryRange.all.collect{|p|[p.range,p.id]},{include_blank: true},{:class=>"selectpicker col-sm-2"}
      = f.input :regulation_id, label: "检定依据" do
        =f.select :regulation_id,Regulation.collect{|p|[p.sn,p.id]},{},{:class=>"selectpicker col-sm-2 chosen-select"}
      = f.association :verification do |f|
        = f.input :organ_id, label: "送检单位" do
          = f.select :organ_id,Organ.all.collect{|p|[p.name,p.id]},{:include=>"_blank"},{:class=>"selectpicker col-sm-2"}
        = f.input :date,label: "送检日期",input_html: {onclick: "WdatePicker({onpicked: function(){$(this).trigger('change')}})"}
      .form-actions
        = f.button :submit,"提交", class: 'btn-info'

javascript:
  $(".chosen-select").chosen();
  var instruments = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    //prefetch: '../data/verifications.json',
    remote: {
      url: '/instruments/search/%QUERY',
      wildcard: '%QUERY'
    }
  });

  $('input.typeahead').typeahead(null, {
    name: 'instruments',
    display: 'sn',
    source: instruments,
    templates: {
      suggestion: function(data){
        return "<div class='custom'><h4>"+data.sn+"</h4><p class='text-muted'><span>"+data.category_type_name+"</span><span class='pull-right'>"+ data.organ_name+"</span></p></div>";
      }
    }
  });
  $('#autofill').click(function(){
    var query_string = $('#instrument_sn').val();
    if(query_string != ""){
      $.ajax({
        type: 'GET',
        url: '/instruments/search',
        data: {query: query_string},
        success: function(data){
          if(data.length != 0){
            var instrument = data[0];
            //$('#verification_instrument_sn').val(query_string);
            $('#instrument_category_type_id').val(instrument.category_type_id);
            $('#instrument_specification').val(instrument.specification);
            $('#instrument_date').val(instrument.date);
            $('#instrument_vendor_id').val(instrument.vendor_id).trigger("chosen:updated");
            $('#instrument_category_id').val(instrument.category_id);
            $('#instrument_category_precision_id').val(instrument.category_precision_id);
            $('#instrument_category_range_id').val(instrument.category_range_id);
            $('#instrument_regulation_id').val(instrument.regulation_id).trigger("chosen:updated");
            //$('#verification_instrument_standard').prop('checked', instrument.standard);
          }else{
            //$('#verification_instrument_sn').val(query_string);
            alert('未找到匹配的计量器具信息。请填写表格信息，添加新的计量器具');
          }
        }
      });
    }else{
      alert('请填写表格信息，添加新的计量器具');
    }
  });

app/views/verifications/organ.slim
= render 'verifications'

app/views/verifications/process_import.slim
link rel="stylesheet" href="/css/typeahead.css"
.widget
  h4
    span.text-info 待检计量器具信息
  hr class="hr-18 dotted hr-double"

  .widgetarea
    a href=imports_verifications_path 继续导入
    div 共导入#{@messages[:count]}条数据
    div 共有#{@messages[:errors].size}条错误数据
    div
      - if @messages[:errors].size > 0
	      span 错误信息：
	      - @messages[:errors].each do |message|
	        div 第#{message[:num]}条数据
	        - message[:errors].each do |m|
	          div= m