config/routes.rb
WdyMeasure::Application.routes.draw do

  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :categories,       only: [:index, :show]
    resources :instrument_kinds, only: [:index, :show]

    resources :instruments,      only: [:create] do
      collection do
        post 'unique'
        post 'search'
      end
    end

    resources :verifications,    only: [:create]
    resources :organs,           only: [:index]
    resources :roles,            only: [:index]

    resources :users,            only: [:index, :create] do
      member do
        post 'approve'
      end
    end

    resources :early_warnings do
      collection do
        get "expires"
        get "scraps"
      end
    end
  end

  resources :notifications, only: [:index, :show]
  get "datalogs" => 'data_logs#index'
  resources :inspections

  resources :notices do
    member do
      get 'edit_inside_page'
      patch 'update_content'
    end
    collection do
      get 'search'
    end
  end

  resources :users
  resources :settings do
    collection do
      get 'organ'
    end
  end

  resources :regulations
  resources :verifications do # 检测检定
    member do
      get 'report'
      get 'certificate'
      post 'calculate'
    end
    collection do
      get 'update_state'
      get 'organ'
      get 'imports'
      post 'process_import'
    end
  end
  resources :reports   # 检定数据报告（检定纪录）
  resources :organs    # 组织单位

  resources :categories do # 分类
    resources :category_types # 类型
    resources :category_ranges # 范围
    resources :category_precisions  # 精度
  end

  get 'instruments/search/:query', to: 'instruments#search', as: 'search'
  get 'instruments/search', to: 'instruments#search'
  resources :instruments do 
    collection do 
      get 'expires'
      get 'scraps'
    end
  end

  resources :vendors
  resources :tasks

  namespace :wdy do
    namespace :unirole do
      resources :organs
      resources :jobs
      resources :users
    end
  end

  resources :instrument_kinds

end

app/models/notification.rb
class Notification < Sequel::Model
  many_to_one :user
  many_to_one :organ
  many_to_one :notice

  def_dataset_method(:unchecked) do
    filter(checked: false).order(:created_at).reverse
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  load_and_authorize_resource

  respond_to :html

  def index
    @page_title = "预警通知"
    @notifications = current_user.notifications_dataset.order(:created_at).reverse
    respond_with(@notifications)
  end

  def show
    @page_title = "预警通知"
    @notification.update(checked: true)
    respond_with(@notification)
  end

  private
    def notification_params
      params.require(:notification).permit(:organ_id, :user_id, :notice_id, :checked, :content, :created_at)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.slim
= simple_form_for(@notification) do |f|
  = f.error_notification

  .form-inputs
    = f.input :organ_id
    = f.input :user_id
    = f.input :notice_id
    = f.input :checked
    = f.input :content

  .form-actions
    = f.button :submit

app/views/notifications/edit.html.slim
h1 Editing notification

== render 'form'

= link_to 'Show', @notification
'|
= link_to 'Back', notifications_path

app/views/notifications/index.html.slim
.table-header
  | 预警通知
.table-responsive
  table.table.table-bordered.table-striped id="notification_table"
    thead
      tr
        th 序号
        th 通知摘要
    tbody
      -@notifications.each_with_index do |notification,index|
          tr
            td = index=index+1
            td
              a class="blue" href=notification_path(notification) data_toggle='tooltip' title="查看详情"
                span class="label #{notification.checked ? "label-default" : "label-yellow"}"
                  = notification.checked ? "已读" : "未读"
              span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true" style="margin-left:15px;"
              | 您的编号为
              = notification.notice.sn
              | 的
              = notification.notice.instrument.detection_name
              | 的证书有效期&nbsp;
              span class="label label-warning"
                | 仅剩余
                = notification.content
              | 了，请贵单位及时查看并重新送检。
              span.pull-right
                = notification.created_at.to_date
javascript:
  var oTable = $('#notification_table').DataTable({
    "oLanguage": {//语言国际化
      //"sUrl": "js/jquery.dataTable.cn.txt"
      "sLengthMenu": "每页显示 _MENU_ 条记录",
      "sZeroRecords": "抱歉， 没有找到",
      "sInfo": "从 _START_ 到 _END_ /共 _TOTAL_ 条数据",
      "sInfoEmpty": "没有数据",
      "sInfoFiltered": "(从 _MAX_ 条数据中检索)",
      "oPaginate": {
      "sFirst": "首页",
      "sPrevious": "前一页",
      "sNext": "后一页",
      "sLast": "尾页"
      },
      "sZeroRecords": "没有检索到数据",
      "sProcessing": "   处理中...",
      "sSearch": "全文搜索"
    },
    "aLengthMenu": [[25, 50, -1], [25, 50, "All"]],
    "scrollX": true,
    "initComplete" : function () {
      $('.dataTables_scroll').parent().removeClass();
      $('#notification_table, .dataTables_scrollHeadInner, .dataTables_scrollHeadInner table').css({"width": "100%"});
      $('.dataTables_scrollFootInner, .dataTables_scrollFootInner table').css({"width": "100%"});
    }
  });

app/views/notifications/new.html.slim
h1 New notification

== render 'form'

= link_to 'Back', notifications_path

app/views/notifications/show.html.slim
.widget
  h3.text-center
    | 预警通知
  p.text-center
    small
      | 发布时间：
      = @notification.created_at.to_date

  .container[style="margin: 0 10% 0 10%;"]
    div
      span
        | 您的编号为
        = @notification.notice.sn
        | 的
        = @notification.notice.instrument.detection_name
        | 的证书有效期
      span class="label label-warning"
        | 仅剩余
        = @notification.content
      | 了，请贵单位及时查看并重新送检。

    hr
    p
      | 证书编号：
      = link_to @notification.notice.sn, notice_path(@notification.notice), target: "_blank"
    p
      | 证书名称：
      = @notification.notice.instrument.detection_name
    p
      | 所属单位：
      = @notification.organ.name
    p
      | 检定时间：
      = @notification.notice.verification_date
    p
      | 有效期至：
      span.label.label-danger
        = @notification.notice.expiry_date