config/routes.rb
WdyMeasure::Application.routes.draw do

  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :categories,       only: [:index, :show]
    resources :instrument_kinds, only: [:index, :show]

    resources :instruments,      only: [:create] do
      collection do
        post 'unique'
        post 'search'
      end
    end

    resources :verifications,    only: [:create]
    resources :organs,           only: [:index]
    resources :roles,            only: [:index]

    resources :users,            only: [:index, :create] do
      member do
        post 'approve'
      end
    end

    resources :early_warnings do
      collection do
        get "expires"
        get "scraps"
      end
    end
  end

  resources :notifications, only: [:index, :show]
  get "datalogs" => 'data_logs#index'
  resources :inspections

  resources :notices do
    member do
      get 'edit_inside_page'
      patch 'update_content'
    end
    collection do
      get 'search'
    end
  end

  resources :users
  resources :settings do
    collection do
      get 'organ'
    end
  end

  resources :regulations
  resources :verifications do # 检测检定
    member do
      get 'report'
      get 'certificate'
      post 'calculate'
    end
    collection do
      get 'update_state'
      get 'organ'
      get 'imports'
      post 'process_import'
    end
  end
  resources :reports   # 检定数据报告（检定纪录）
  resources :organs    # 组织单位

  resources :categories do # 分类
    resources :category_types # 类型
    resources :category_ranges # 范围
    resources :category_precisions  # 精度
  end

  get 'instruments/search/:query', to: 'instruments#search', as: 'search'
  get 'instruments/search', to: 'instruments#search'
  resources :instruments do 
    collection do 
      get 'expires'
      get 'scraps'
    end
  end

  resources :vendors
  resources :tasks

  namespace :wdy do
    namespace :unirole do
      resources :organs
      resources :jobs
      resources :users
    end
  end

  resources :instrument_kinds

end

app/models/category.rb
# -*- coding: utf-8 -*-
# 检测分类
class Category < Sequel::Model(:categories)
  plugin :validation_helpers
  plugin :active_model

  # one_to_many :category_precisions,class_name: "CategoryPrecision"
  # one_to_many :category_types,class_name: "CategoryType"
  # one_to_many :category_ranges,class_name: "CategoryRange"
  one_to_many :instrument_kinds, class_name: "InstrumentKind"
  one_to_many :vendors, class_name: "Vendor"
  one_to_many :regulations, class_name: "Regulation"

  def validate
      super
      #validates_unique [:name]
    end
end

app/models/category_type.rb
# -*- coding: utf-8 -*-
#  检测类型
class CategoryType < Sequel::Model(:category_types)
  plugin :validation_helpers
  plugin :active_model
  many_to_one :category,class_name: "Category"

  def self.with_report
    permit_calculation = %w(数字压力计 弹性元件式一般压力表 常用玻璃量器 砝码 架盘天平 电子天平)
    self.where(name: permit_calculation)
  end

  def validate
    super
    #validates_unique [:name]
  end
end

app/controllers/api/categories_controller.rb
# -*- coding: UTF-8 -*-

# 检定类别
class Api::CategoriesController < ActionController::Base
    def index
        render json: Category.all
    end

    def show
        category = Category[params[:id]]
        category[:device_types] = category.instrument_kinds
        render json: category
    end
end

app/controllers/categories_controller.rb
# -*- coding: UTF-8 -*-
# 检测分类
class CategoriesController < ApplicationController
  load_and_authorize_resource class: "Category"

  def index
    @page_title = "检测分类管理"

    respond_to do |format|
      format.html
      format.json { render json: @categories, layout: false }
    end
  end

  def show
    @category = Category[params[:id]]
    @page_title = @category.name + "分类"


  end



  def create
    @category =  Vendor.new(params[:category])
    if @category.save
      redirect_to :action =>:index
    else
      render :action=>:new
    end
  end

  def update

    if @category.update(params[:category])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to :action => :index
  end


end

app/views/categories/_form.slim
=f.input :name,:label => "名称"

.form-actions
  = f.button :submit,"保存"

app/views/categories/edit.slim
.widget
  h4
    span.text-info 编辑分类信息
  hr class="hr-18 dotted hr-double"
  .widgetarea
    = simple_form_for @category, :html => {:class=>"form-horizontal form-mini"} do |f|
      =render "form",:f =>f

app/views/categories/index.slim
.table-header
  | 检测分类
  div class="widget-toolbar no-border"
    a  class="btn btn-primary"  href=new_category_path 添加
.table-responsive
  table.table.table-bordered.table-striped.table-hover.dataTable
    thead
      tr
        th 序号
        th 名称
        th
    tbody
      -@categories.each_with_index do |category,index|
          tr
            td =index=index+1
            td =category.name
            td
              div class="pull-right action-buttons"
                //a class="blue" href=category_path(category) data_toggle='tooltip' title="显示"
                //  i class="icon-zoom-in  bigger-130"


                a class="blue" href=edit_category_path(category) data_toggle='tooltip' title="编辑"
                  i class="fa fa-edit"

                //span class="vbar"
                //=link_to "<i class='fa fa-trash'></i>".html_safe,category_path(category),method: "delete",data_toggle: 'tooltip', title: "删除",confirm: "您确定要删除此类型？",class: "red"
                span class="vbar"

app/views/categories/new.slim
.widget
  h4
    span.text-info 添加分类
  hr class="hr-18 dotted hr-double"
  
  .widgetarea
    = simple_form_for @category, :html => {:class=>"form-horizontal form-mini"} do |f|
      =render "form",:f =>f

app/views/categories/show.slim
.widget
  h4
    span.text-info =@page_title
    div class="widget-toolbar no-border"
          a  class="btn btn-minier btn-primary"  href=categories_path 返回
  hr class="hr-18 dotted hr-double"
  .widgetarea

    div class="widget-box col-md-4"
      .table-header
        | 检测类型
        div class="widget-toolbar no-border"
          a  class="btn btn-primary"  href=new_category_category_type_path(params[:id]) 添加检测类型
      div class="widget-body"
        div class="widget-main"
          .table-responsive
            table.table.table-bordered.table-striped.table-hover.dataTable
              thead
                tr
                  th 序号
                  th 名称
                  th
              tbody
                -@category.category_types.each_with_index do |category,index|
                    tr
                      td =index=index+1
                      td =category.name
                      td
                        div class="pull-right action-buttons"
                          a class="blue" href=edit_category_category_type_path(params[:id],category) data_toggle='tooltip' title="编辑"
                            i class="icon-pencil bigger-130"

                          span class="vbar"
                          =link_to "<i class='icon-trash bigger-130'></i>".html_safe,category_category_type_path(params[:id],category),method: "delete", data_toggle: 'tooltip', title: "删除", confirm: "您确定要删除此类型？",class: "red"
                          span class="vbar"

    div class="col-md-1" style="width: 30px;"

    div class="widget-box col-md-3"
      .table-header
        | 检测精度
        div class="widget-toolbar no-border"
          a  class="btn btn-primary"  href=new_category_category_precision_path(params[:id]) 添加检测精度
      div class="widget-body"
        div class="widget-main"
          .table-responsive
            table.table.table-bordered.table-striped.table-hover.dataTable
              thead
                tr
                  th 序号
                  th 名称
                  th
              tbody
                -@category.category_precisions.each_with_index do |category,index|
                    tr
                      td =index=index+1
                      td =category.name
                      td
                        div class="pull-right action-buttons"
                          a class="blue" href=edit_category_category_precision_path(params[:id],category) data_toggle='tooltip' title="编辑"
                            i class="icon-pencil bigger-130"

                          span class="vbar"
                          =link_to "<i class='icon-trash bigger-130'></i>".html_safe,category_category_precision_path(params[:id],category),method: "delete", data_toggle: 'tooltip', title: "删除", confirm: "您确定要删除此类型？",class: "red"
                          span class="vbar"


    div class="col-md-1" style="width: 30px;"

    div class="widget-box col-md-4"
      .table-header
        | 检测范围
        div class="widget-toolbar no-border"
          a  class="btn btn-primary"  href=new_category_category_range_path(params[:id]) 添加检测范围
      div class="widget-body"
        div class="widget-main"
          .table-responsive
            table.table.table-bordered.table-striped.table-hover.dataTable
              thead
                tr
                  th 序号
                  th 范围
                  th 单位
                  th
              tbody
                -@category.category_ranges.each_with_index do |category,index|
                    tr
                      td =index=index+1
                      td =category.range
                      td = category.unit
                      td
                        div class="pull-right action-buttons"
                          a class="blue" href=edit_category_category_range_path(params[:id],category) data_toggle='tooltip' title="编辑"
                            i class="icon-pencil bigger-130"

                          span class="vbar"
                          =link_to "<i class='icon-trash bigger-130'></i>".html_safe,category_category_range_path(params[:id],category),method: "delete", data_toggle: 'tooltip', title: "删除", confirm: "您确定要删除此类型？",class: "red"
                          span class="vbar"