config/routes.rb
WdyMeasure::Application.routes.draw do

  root 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    resources :categories,       only: [:index, :show]
    resources :instrument_kinds, only: [:index, :show]

    resources :instruments,      only: [:create] do
      collection do
        post 'unique'
        post 'search'
      end
    end

    resources :verifications,    only: [:create]
    resources :organs,           only: [:index]
    resources :roles,            only: [:index]

    resources :users,            only: [:index, :create] do
      member do
        post 'approve'
      end
    end

    resources :early_warnings do
      collection do
        get "expires"
        get "scraps"
      end
    end
  end

  resources :notifications, only: [:index, :show]
  get "datalogs" => 'data_logs#index'
  resources :inspections

  resources :notices do
    member do
      get 'edit_inside_page'
      patch 'update_content'
    end
    collection do
      get 'search'
    end
  end

  resources :users
  resources :settings do
    collection do
      get 'organ'
    end
  end

  resources :regulations
  resources :verifications do # 检测检定
    member do
      get 'report'
      get 'certificate'
      post 'calculate'
    end
    collection do
      get 'update_state'
      get 'organ'
      get 'imports'
      post 'process_import'
    end
  end
  resources :reports   # 检定数据报告（检定纪录）
  resources :organs    # 组织单位

  resources :categories do # 分类
    resources :category_types # 类型
    resources :category_ranges # 范围
    resources :category_precisions  # 精度
  end

  get 'instruments/search/:query', to: 'instruments#search', as: 'search'
  get 'instruments/search', to: 'instruments#search'
  resources :instruments do 
    collection do 
      get 'expires'
      get 'scraps'
    end
  end

  resources :vendors
  resources :tasks

  namespace :wdy do
    namespace :unirole do
      resources :organs
      resources :jobs
      resources :users
    end
  end

  resources :instrument_kinds

end

app/models/report.rb
# -*- coding: utf-8 -*-
# 检定纪录报告
class Report < Sequel::Model(:reports)
  one_to_one :verification,class_name: "Verification" # 检定申请纪录

  # report == Verification
  # record == report
  # Examine::RecordRepo => Report
  # Examine::RecordDomain => Report
  class << self
    def default_data verification
      @report = verification
      record = File.read("lib/records/#{Settings.records.send("#{verification.instrument.instrument_kind.name}")}")
      self.instance_eval(record)
    end

    def verify verification, args = {}
      @record = args.empty? ? Report.default_data(verification) : args
      byebug
      # verification.update(standard_id: args['标准器']) if args['标准器']

      record_inst = Report.first(verification_id: verification.id)
      unless record_inst
        record_inst = Report.create(verification_id: verification.id, data: @record.to_json)
      else
        record_inst = record_inst.update(data: @record.to_json)
      end

      calculate = File.read("lib/calculates/#{Settings.calculates.send("#{verification.instrument.instrument_kind.name}")}")
      calculates  = self.instance_eval(calculate)

      record_inst = Report.first(verification_id: verification.id)
      unless record_inst
        record_inst = Report.create(verification_id: verification.id, data: calculates.to_json)
      else
        record_inst.update(data: calculates.to_json)
      end

      @facts = calculates["计算结果"]
      rule   = File.read("lib/rules/#{Settings.rules.send("#{verification.instrument.instrument_kind.name}")}")
      valid  = self.instance_eval(rule)

      # 将验证结果存到 data 中
      record_inst.update(data: calculates.merge({result: valid}).to_json)

      JSON.parse(record_inst.data)
    end
  end

  def record
    self.data
  end
end

app/controllers/reports_controller.rb
# -*- coding: UTF-8 -*-
# 检测检定 
class ReportsController < ApplicationController
  load_and_authorize_resource class: "Report"
end

app/views/reports/flexible_genernal_pressure_gauge.html.erb
<% report = @data %>
<div class="container">
    <h2 class="center" style="margin-bottom: 50px;">
      <i class="fa fa-tasks"></i>
      <span> 弹性元件式一般压力表检定记录</span>
    </h2>

  <div>
    <%= simple_form_for :report, url: calculate_verification_path, method: :post do |f| %>
    <table class="table table-noborder">
      <tr><td>记录编号：<input name="report[纪录编号]" type="text"  value="<%= @verification.sn%>"/></td></tr>
      <tr>
        <td width="33%">送检单位 <span class="input-line"> <%= @verification.organ.name%></span></td>
        <td width="33%">被检表名称<span class="input-line"> <%= @verification.instrument.category_type.name%></span></td>
        <td width="34%">制造商<span class="input-line"> <%= @verification.instrument.vendor.name%></span></td>
      </tr>
      <tr>
        <td>出厂编号 <span class="input-line"> <%= @verification.instrument.sn %></span></td>
        <td>测量范围 <span class="input-line"> <%= @verification.instrument.detection_range%></span></td>
        <input type="hidden" name=report[测量范围上限] value="<%= @verification.instrument.category_range.try(:start)%>">
        <input type="hidden" name=report[测量范围下限] value="<%= @verification.instrument.category_range.try(:end)%>">
        <td>准确度等级 <span class="input-line"> <%= @verification.instrument.category_precision.try(:name)%></span></td>
        <input type="hidden" name=report[准确度等级] value="<%= @verification.instrument.category_precision.try(:name)%>">
      </tr>
      <tr>
        <td>分度值 <input value="<%= report['分度值']%>" type="text" name="report[分度值]" class="input-line" /></td>
        <td>最大允许误差 <span class="input-line"> <%= report['计算结果']['最大允许误差'] if report['计算结果'].present? %></span></td>
        <td></td>
      </tr>
      <tr>
        <td>检定温度 <input type="text" value="<%= report['计算结果']['检定温度']%>" name="report[计算结果][检定温度]"  class="input-line"/>&#8451;</td>
        <td>相对湿度 <input type="text" value="<%= report['计算结果']['相对湿度']%>" name="report[计算结果][相对湿度]" class="input-line">%</td>
        <td></td>
      </tr>
      <tr>
        <td>标准器名称
           <%= select_tag 'report[标准器]', options_for_select([*@instruments].collect{|i| [i.sn, i.id]}, @data['标准器']),{prompt: '请选择', onchange: "changeStandardInstrument(this.value)"}%>
        </td>
        <td>准确度等级 <span class="input-line" id="sd_precision"></span></td>
        <td>测量范围<span class="input-line" id="sd_range"></span></td>
      </tr>
      <tr>
        <td>1.外观检查
          <select name="report[计算结果][外观检查]" style="width:150px;">
            <option value="合格" <%= report['计算结果']['外观检查'] == '合格' ? 'selected' : ""%>>合格</option>
            <option value="不合格" <%= report['计算结果']['外观检查'] == '不合格' ? 'selected' : ""%>>不合格</option>
          </select>
          <div class="clearfix"></div>
        </td>
        <td>2.零位误差
          <select name="report[计算结果][零位误差]" style="width:150px;">
            <option value="合格" <%= report['计算结果']['零位误差'] == '合格' ? 'selected' : ""%>>合格</option>
            <option value="不合格" <%= report['计算结果']['零位误差'] == '不合格' ? 'selected' : ""%>>不合格</option>
          </select>
          <div class="clearfix"></div>
        </td>
        <td> 3.指针偏转平稳性
          <select name="report[计算结果][指针偏转平稳性]" style="width:150px;">
            <option value="合格" <%= report['计算结果']['指针偏转平稳性'] == '合格' ? 'selected' : ""%>>合格</option>
            <option value="不合格" <%= report['计算结果']['指针偏转平稳性'] == '不合格' ? 'selected' : ""%>>不合格</option>
          </select>
          <div class="clearfix"></div>
        </td>
      </tr>
      <tr>
        <td colspan="3">4.示值检定</td>
      </tr>
    </table>
  <div class="table-responsive">
    <table class="table table-bordered center">
      <tr>
        <td rowspan="2" style="min-width: 110px;">标准器的压力值</td>
        <td colspan="2">轻敲表壳后被检仪表示值</td>
        <td colspan="2">轻敲位移</td>
        <td rowspan="2" style="min-width: 70px;">最大示值误差</td>
        <td rowspan="2" style="min-width: 70px;">最大回程误差</td>
      </tr>
      <tr>
        <td style="min-width: 110px;">升压</td>
        <td style="min-width: 110px;">降压</td>
        <td style="min-width: 110px;">升压</td>
        <td style="min-width: 110px;">降压</td>
      </tr>
      <% 7.times do |index|%>
        <tr>
          <td colspan="1"><input style="width: 70%;" value="<%= report['示值检定']['标准器的压力值'][index]%>" type="text" name="report[示值检定][标准器的压力值][]"></td>
          <td colspan="1"><input style="width: 70%;" value="<%= number_with_precision(report['示值检定']['轻敲表壳后被检仪表示值']['升压'][index],precision: 3)%>" type="text" name="report[示值检定][轻敲表壳后被检仪表示值][升压][]"></td>
          <td colspan="1"><input style="width: 70%;" value="<%= number_with_precision(report['示值检定']['轻敲表壳后被检仪表示值']['降压'][index],precision: 3)%>" type="text" name="report[示值检定][轻敲表壳后被检仪表示值][降压][]"></td>
          <td colspan="1"><span style="width: 70%;"><%= number_with_precision(report['计算结果']['轻敲位移']['升压'][index],precision: 3)%></span></td>
          <td colspan="1"><span style="width: 70%;"><%= number_with_precision(report['计算结果']['轻敲位移']['降压'][index],precision: 3)%></span></td>
          <% if index.zero? %>
            <td rowspan="7"><%= number_with_precision(report['计算结果']['最大示值误差'],precision: 3) if report['计算结果'].present? %></td>
            <td rowspan="7"><%= number_with_precision(report['计算结果']['最大回程误差'],precision: 3) if report['计算结果'].present? %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <table class="table table-noborder">
      <tr>
        <td colspan="3" class="text-left">5.其他：
          <select name="report[计算结果][其他]" style="width:150px;">
            <option value="合格" <%= report['计算结果']['其他'] == '合格' ? 'selected' : ""%>>合格</option>
            <option value="不合格" <%= report['计算结果']['其他'] == '不合格' ? 'selected' : ""%>>不合格</option>
          </select>
        </td>
      <tr>
      </tr>
        <td colspan="3" >结论：根据以上各项检定结果，该压力表 <span class="input-line">
            <% if report['result'].present? %>
              <% if report['result']['pass'] == true %>
                <span class="blue">
                <%= "符合#{@verification.instrument.category_precision.try(:name)}级"%>
                </span>
              <% else %>
                <span class="red">
                  <%= "不符合#{@verification.instrument.category_precision.try(:name)}级"%>
                </span>
                <%= render partial: 'failure', locals: {message: report['result']['message']} %>
              <% end %>
            <% end %>
        </span>
      </td>
      </tr>
      <tr>
        <td>检定员：<input type="text" name="report[检定员]" class="input-line" value="<%= report['检定员']%>"/></td>
        <td>
          <span style="display: block;margin-top:6px;">检定日期：
            <input type="text" name="report[检定日期]" value="<%= report['检定日期']%>" onClick="WdatePicker({onpicked: function(){$(this).trigger('change')}})" readonly='true'  class="input-time"/>
          </span>
        </td>
        <td>审核员：<input type="text" name="report[核验员]" class="input-line" value="<%= report['核验员']%>"/></td>
        <td>
          <span style="display: block;margin-top:6px;">核验日期：
            <input type="text" name="report[核验日期]" value="<%= report['核验日期']%>" onClick="WdatePicker({onpicked: function(){$(this).trigger('change')}})" readonly='true'  class="input-time"/>
          </span>
        </td>
      </tr>
      </table>
    </div>
    <div class="text-right">
      <% if can? :calculate, Verification%>
        <% if !@verification.approved? %>
          <%= f.submit "提交", class: "btn btn-success btn-sm" %>
        <% end %>
        <% if @data['result']%>
          <%= link_to (@data['result']['pass'] ? '查看证书' : '查看通知书'), certificate_verification_path(@verification,:format => :pdf), target: '_blank', class: 'btn btn-success btn-sm'%>
        <% end %>
      <% end %>
    </div>
    <% end %>
    </div>
  </div>

<script>
  window.onload = changeStandardInstrument("<%= @data['标准器']%>");

  function changeStandardInstrument(id){
    if(id != ""){
      $.ajax({
        url: window.location.origin + '/instruments/' + id,
        method: 'GET',
        success: function(data){
          $('#sd_range').html(data.range);
          $('#sd_precision').html(data.precision);
        }
      });
    }else{
      $('#sd_range').empty();
      $('#sd_precision').empty();
    }
  }
</script>

app/views/reports/gas_displacement_meter.html.erb
<% report = @data %>

<%= simple_form_for :report, url: calculate_verification_path, method: :post do |f| %>

  <div class="container">

    <h3 class="title">
      <span>容积式流量计（A类）检定记录</span>
    </h3>

    <div class="table-responsive">
      <table class="table table-noborder">
        <tr>
          <td class="align-left">计量器具名称：</td>
          <td>涡轮流量计</td>
          <td class="align-left">规格型号：</td>
          <td>TBQZ-50B</td>
          <td class="align-left">大气压力：</td>
          <td><input type="text" value="<%= report['大气压力']%>" name="report[大气压力]"> kPa</td>
        </tr>
        <tr>
          <td class="align-left">制造单位：</td>
          <td>天信仪表</td>
          <td class="align-left">准确度等级：</td>
          <td>1.5级</td>
          <td class="align-left">环境温度：</td>
          <td><input type="text" value="<%= report['环境温度1']%>" name="report[环境温度1]"> &deg;C</td>
        </tr>
        <tr>
          <td class="align-left">送检单位：</td>
          <td>泸州西部公司</td>
          <td class="align-left">出厂编号：</td>
          <td>X4085050</td>
          <td class="align-left">环境温度：</td>
          <td><input type="text" value="<%= report['环境温度2']%>" name="report[环境温度2]"> &#37;</td>
        </tr>
        <tr>
          <td class="align-left">标准装置名称：</td>
          <td>音速喷嘴法气体流量标准装置</td>
          <td class="align-left">装置测量不确定度：</td>
          <td>0.25&#37;（k=2）</td>
          <td class="align-left">检定介质：</td>
          <td><input type="text" value="<%= report['检定介质']%>" name="report[检定介质]"></td>
        </tr>
        <tr>
          <td class="align-left">标准装置型号：</td>
          <td>LXH-600</td>
          <td class="align-left">标准装置编号：</td>
          <td>1108006</td>
          <td class="align-left">依据技术规范：</td>
          <td><input type="text" value="<%= report['依据技术规范']%>" name="report[依据技术规范]"></td>
        </tr>
      </table>
      
    
      <table class="table table-bordered top-25 align-center">
        <thead>
          <tr>
            <td>喷嘴编号</td>
            <td>检定流量<br>（m<sup>3</sup>/h）</td>
            <td>检定体积<br>（m<sup>3</sup>）</td>
            <td>检定时间<br>（s）</td>
            <td>流量计脉冲数</td>
            <td>流量计压力<br>（kPa）</td>
            <td>流量计温度<br>（&deg;C）</td>
            <td>喷嘴压力<br>（kPa）</td>
            <td>喷嘴温度<br>（&deg;C）</td>
            <td>仪表系数<br>（1/m<sup>3</sup>）</td>
            <td>平均仪表系数<br>（1/m<sup>3</sup>）</td>
            <td>线性度<br> &#37;</td>
            <td>重复性<br> &#37;</td>
          </tr>
        </thead>
        <tbody>
          <% 4.times do |k| %>
            <% k = k+1 %>
            <tr>
              <td rowspan="3"><input class="input-small" type="text" value="<%= report['喷嘴编号'+k.to_s]%>" name="report[喷嘴编号<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定流量1'+k.to_s]%>" name="report[检定流量1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定体积1'+k.to_s]%>" name="report[检定体积1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定时间1'+k.to_s]%>" name="report[检定时间1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计脉冲1'+k.to_s]%>" name="report[流量计脉冲1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计压力1'+k.to_s]%>" name="report[流量计压力1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计温度1'+k.to_s]%>" name="report[流量计温度1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴压力1'+k.to_s]%>" name="report[喷嘴压力1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴温度1'+k.to_s]%>" name="report[喷嘴温度1<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['仪表系数1'+k.to_s]%>" name="report[仪表系数1<%=k%>]"></td>
              <td rowspan="3"><input class="input-small" type="text" value="<%= report['平均仪表系数'+k.to_s]%>" name="report[平均仪表系数<%=k%>]"></td>
              <td rowspan="3"><input class="input-small" type="text" value="<%= report['线性度'+k.to_s]%>" name="report[线性度<%=k%>]"></td>
              <td rowspan="3"><input class="input-small" type="text" value="<%= report['重复性'+k.to_s]%>" name="report[重复性<%=k%>]"></td>
            </tr>
            <tr>
              <td><input class="input-small" type="text" value="<%= report['检定流量2'+k.to_s]%>" name="report[检定流量2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定体积2'+k.to_s]%>" name="report[检定体积2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定时间2'+k.to_s]%>" name="report[检定时间2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计脉冲2'+k.to_s]%>" name="report[流量计脉冲2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计压力2'+k.to_s]%>" name="report[流量计压力2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计温度2'+k.to_s]%>" name="report[流量计温度2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴压力2'+k.to_s]%>" name="report[喷嘴压力2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴温度2'+k.to_s]%>" name="report[喷嘴温度2<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['仪表系数2'+k.to_s]%>" name="report[仪表系数2<%=k%>]"></td>
            </tr>
            <tr>
              <td><input class="input-small" type="text" value="<%= report['检定流量3'+k.to_s]%>" name="report[检定流量3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定体积3'+k.to_s]%>" name="report[检定体积3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['检定时间3'+k.to_s]%>" name="report[检定时间3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计脉冲3'+k.to_s]%>" name="report[流量计脉冲3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计压力3'+k.to_s]%>" name="report[流量计压力3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['流量计温度3'+k.to_s]%>" name="report[流量计温度3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴压力3'+k.to_s]%>" name="report[喷嘴压力3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['喷嘴温度3'+k.to_s]%>" name="report[喷嘴温度3<%=k%>]"></td>
              <td><input class="input-small" type="text" value="<%= report['仪表系数3'+k.to_s]%>" name="report[仪表系数3<%=k%>]"></td>
            </tr>
          <% end %>


          

          <tr>
            <td>备注：</td>
            <td colspan="12"><input class="percent-80" value="<%= report['备注']%>" name="report[备注]"></td>
          </tr>

          <tr>
            <td rowspan="3">检定结果<input class="input-small" value="<%= report['检定结果']%>" name="report[检定结果]"></td>
            <td colspan="12">
              仪表系数Km=19924.413 1/m<sup>3</sup> &nbsp;
              &lt;0.2Qmax线性度=2.794 &#37;&nbsp;   
              &lt;0.2Qmax重复性误差=0.052 &#37; &nbsp; 
              &ge;0.2Qmax线性度=0.539 &#37; &nbsp;
              &ge;0.2Qmax重复性误差=0.031 &#37; 
            </td>
          </tr>
          <tr>
            <td colspan="4">检定流量范围：<input type="text" value="<%= report['检定流量范围']%>" name="report[检定流量范围]">m<sup>3</sup>/</td>
            <td colspan="4">
              检定结论：
              <input type="text" value="<%= report['检定结论']%>" name="report[检定结论]">
            </td>
            <td colspan="4">
              检定日期：
              <input type="text" value="<%= report['检定日期']%>" name="report[检定日期]">
            </td>
          </tr>

          <tr>
            <td colspan="4">
              检定员：
              <input type="text" value="<%= report['检定员']%>" name="report[检定员]">
            </td>
            <td colspan="4">
              核验员：
              <input type="text" value="<%= report['核验员']%>" name="report[核验员]">
            </td>
            <td colspan="4">
              检定单位：
              <input type="text" value="<%= report['检定单位']%>" name="report[检定单位]">
            </td>
          </tr>

        </tbody>
      </table>

    </div>

  </div>
  <div class="text-right" >
    <% if can? :calculate, Verification%>
      <% if !@verification.approved? %>
        <%= f.submit "提交", class: "btn btn-success btn-sm" %>
      <% end %>
      <% if report['qualified'] && @verification.approved? %>
        <%= link_to (report['qualified'] ? '查看证书' : '查看通知书'), notice_path(@verification.notice,:format => :pdf), target: '_blank', class: 'btn btn-success btn-sm'%>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/reports/working_glass_container.html.erb
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <title>T44-1</title>
  <script type="text/javascript" src="../libs/include.js"></script>
  <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
  <div class="container">
    <h3 class="title">
      <span>常用玻璃器衡量法检定记录</span>
    </h2>
    <div>
      <table class="table table-noborder align-center">
        <tr>
          <td rowspan="4">标称容量</td>
          <td rowspan="4"><input type="text" value="25"></td>
        </tr>
        <tr>
          <td rowspan="2">容量允差</td>
          <td>A&plusmn;</td>
          <td class="align-right">检定室温度</td>
          <td class="align-left"><input type="text" value="16"></td>
          <td rowspan="2">
            <select>
              <option>合格</option>
              <option>不合格</option>
            </select>
          </td>
        </tr>
        <tr>
          <td>B&plusmn;</td>
          <td class="align-right">纯水温度</td>
          <td class="align-left"><input type="text" value="15.5"></td>
        </tr>
        <tr>
          <td colspan="3" class="align-right"><strong>任意两检定点之间的最大误差</strong></td>
          <td class="align-left"><input type="text" value="16"></td>
          <td>
            <select>
              <option>合格</option>
              <option>不合格</option>
            </select>
          </td>
        </tr>
      </table>


      <div class="table-responsive">
        <h3 class="title">纯水质量检定记录</h3>
        <table class="table table-bordered align-center">
          <thead>
            <tr>
              <td>序号</td>
              <td>检定点/ml</td>
              <td>实测质量/g</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td></td>
              <td><input type="text" value="5"></td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input type="text" value="10"></td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input type="text" value="15"></td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input type="text" value="20"></td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td><input type="text" value="25"></td>
              <td></td>
            </tr>
          </tbody>
        </table>


        <h3 class="title">检定结果的计算</h3>
        <table class="table table-bordered align-center">
          <thead>
            <tr>
              <td>序号</td>
              <td>K（t）值</td>
              <td>实际容量V20/ml</td>
              <td>容量偏差/ml</td>
              <td>检定结果</td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td></td>
              <td>1.00354</td>
              <td><input type="text" value="4.986"></td>
              <td><input type="text" value="-0.014"></td>
              <td>
                <select>
                  <option>合格</option>
                  <option>不合格</option>
                </select>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>1.00354</td>
              <td><input type="text" value="4.986"></td>
              <td><input type="text" value="-0.014"></td>
              <td>
                <select>
                  <option>合格</option>
                  <option>不合格</option>
                </select>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>1.00354</td>
              <td><input type="text" value="4.986"></td>
              <td><input type="text" value="-0.014"></td>
              <td>                
                <select>
                  <option>合格</option>
                  <option>不合格</option>
                </select>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>1.00354</td>
              <td><input type="text" value="4.986"></td>
              <td><input type="text" value="-0.014"></td>
              <td>
                <select>
                  <option>合格</option>
                  <option>不合格</option>
                </select>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>1.00354</td>
              <td><input type="text" value="4.986"></td>
              <td><input type="text" value="-0.014"></td>
              <td>                
                <select>
                  <option>合格</option>
                  <option>不合格</option>
                </select>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</body>
</html>